source 'https://rubygems.org'
gem 'sqlite3'
gem 'sequel'
gem 'discordrb', github: 'shardlab/discordrb', tag: 'v3.4.2'
gem 'discordrb-webhooks', '3.4.2'
gem 'rufus-scheduler'
gem 'tzinfo'
gem 'tzinfo-data'
